### ISSUE TITLE
ntopng: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by katacarbix** [edgd1er/ntopng-docker#3]
I'm trying to run this image on a Raspberry Pi 4 with Arch Linux ARM.

Here is my compose file:

```yaml
version: "3.3"
services:
  ntop:
    image: edgd1er/ntopng:dev-latest
    restart: unless-stopped
    command: --community -d /var/lib/ntopng -i eth0 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - TZ=America/Chicago
      - NTOP_UID=1000
      - NTOP_GID=1000
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: --save 900 1
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
```

The image starts, however the webpage is inaccessible and the docker-compose log shows this:
```
ntop_1       | + setTimeZone
ntop_1       | + [[ -z America/Chicago ]]
ntop_1       | ++ cat /etc/timezone
ntop_1       | + [[ America/Chicago == America/Chicago ]]
ntop_1       | + return
ntop_1       | + setUid
ntop_1       | + '[' -n 1000 ']'
ntop_1       | ++ id -u ntopng
ntop_1       | + '[' 1000 -ne 1000 ']'
ntop_1       | + setGid
ntop_1       | + '[' '!' -z 1000 ']'
ntop_1       | ++ id -g ntopng
ntop_1       | + '[' '!' 1000 -eq 1000 ']'
ntop_1       | + ntopng --community -d /var/lib/ntopng -i eth0 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
ntop_1       | ntopng: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
```

My guess is that `libcap` wasn't installed when building the image since I can't find any results for it when searching in this repo.
